<?php if ( ! defined( 'ABSPATH' ) ) {
	die( 'Cheatin&#8217; uh?' );
}

/* ==========================================================================
	Available AddThis Services
============================================================================= */

if( ! function_exists( 'helium_addthis_services' ) ):

function helium_addthis_services() {
	return array(

		/* External Services */
		'facebook_like'         => esc_html__( 'Facebook Like', 'helium' ), 
		'facebook_send'         => esc_html__( 'Facebook Send', 'helium' ), 
		'tweet'                 => esc_html__( 'Twitter Tweet', 'helium' ), 
		'twitter_follow_native' => esc_html__( 'Twitter Follow', 'helium' ), 
		'google_plusone'        => esc_html__( 'Google+ One', 'helium' ), 
		'google_plusone_badge'  => esc_html__( 'Google+ Badge', 'helium' ), 
		'hyves_respect'         => esc_html__( 'Hyves Respect', 'helium' ), 
		'linkedin_counter'      => esc_html__( 'LinkedIn', 'helium' ), 
		'stumbleupon_badge'     => esc_html__( 'StumbleUpon Badge', 'helium' ), 
		'pinterest_pinit'       => esc_html__( 'Pinterest Pinit', 'helium' ), 
		'foursquare'            => esc_html__( 'Foursquare', 'helium' ), 
		'amazonwishlist'        => esc_html__( 'Amazon Wishlist', 'helium' ), 

		/* Native Services */
		'compact'               => esc_html__( 'AddThis Compact', 'helium' ), 
		'expanded'              => esc_html__( 'AddThis Expanded', 'helium' ), 
		'100zakladok'           => esc_html__( '100zakladok', 'helium' ), 
		'2tag'                  => esc_html__( '2 Tag', 'helium' ), 
		'2linkme'               => esc_html__( '2linkme', 'helium' ), 
		'a97abi'                => esc_html__( 'A97abi', 'helium' ), 
		'addressbar'            => esc_html__( 'Address Bar', 'helium' ), 
		'adfty'                 => esc_html__( 'Adfty', 'helium' ), 
		'adifni'                => esc_html__( 'Adifni', 'helium' ), 
		'advqr'                 => esc_html__( 'ADV QR code', 'helium' ), 
		'amazonwishlist'        => esc_html__( 'Amazon', 'helium' ), 
		'amenme'                => esc_html__( 'Amen Me!', 'helium' ), 
		'aim'                   => esc_html__( 'Aol Lifestream', 'helium' ), 
		'aolmail'               => esc_html__( 'AOL Mail', 'helium' ), 
		'apsense'               => esc_html__( 'APSense', 'helium' ), 
		'arto'                  => esc_html__( 'Arto', 'helium' ), 
		'azadegi'               => esc_html__( 'Azadegi', 'helium' ), 
		'baang'                 => esc_html__( 'Baang', 'helium' ), 
		'baidu'                 => esc_html__( 'Baidu', 'helium' ), 
		'balltribe'             => esc_html__( 'BallTribe', 'helium' ), 
		'beat100'               => esc_html__( 'Beat100', 'helium' ), 
		'biggerpockets'         => esc_html__( 'BiggerPockets', 'helium' ), 
		'bitly'                 => esc_html__( 'Bit.ly', 'helium' ), 
		'bizsugar'              => esc_html__( 'bizSugar', 'helium' ), 
		'bland'                 => esc_html__( 'Bland takkinn', 'helium' ), 
		'blinklist'             => esc_html__( 'Blinklist', 'helium' ), 
		'blogger'               => esc_html__( 'Blogger', 'helium' ), 
		'bloggy'                => esc_html__( 'Bloggy', 'helium' ), 
		'blogkeen'              => esc_html__( 'Blogkeen', 'helium' ), 
		'blogmarks'             => esc_html__( 'Blogmarks', 'helium' ), 
		'blurpalicious'         => esc_html__( 'Blurpalicious', 'helium' ), 
		'bobrdobr'              => esc_html__( 'Bobrdobr', 'helium' ), 
		'bonzobox'              => esc_html__( 'BonzoBox', 'helium' ), 
		'socialbookmarkingnet'  => esc_html__( 'BookmarkingNet', 'helium' ), 
		'bookmarkycz'           => esc_html__( 'Bookmarky.cz', 'helium' ), 
		'bookmerkende'          => esc_html__( 'Bookmerken', 'helium' ), 
		'box'                   => esc_html__( 'Box.net', 'helium' ), 
		'brainify'              => esc_html__( 'Brainify', 'helium' ), 
		'bryderi'               => esc_html__( 'Bryderi', 'helium' ), 
		'buddymarks'            => esc_html__( 'BuddyMarks', 'helium' ), 
		'buffer'                => esc_html__( 'Buffer', 'helium' ), 
		'buzzzy'                => esc_html__( 'Buzzzy', 'helium' ), 
		'camyoo'                => esc_html__( 'Camyoo', 'helium' ), 
		'care2'                 => esc_html__( 'Care2', 'helium' ), 
		'foodlve'               => esc_html__( 'Cherry Share', 'helium' ), 
		'chiq'                  => esc_html__( 'Chiq', 'helium' ), 
		'cirip'                 => esc_html__( 'Cirip', 'helium' ), 
		'citeulike'             => esc_html__( 'CiteULike', 'helium' ), 
		'classicalplace'        => esc_html__( 'ClassicalPlace', 'helium' ), 
		'cleanprint'            => esc_html__( 'CleanPrint', 'helium' ), 
		'cleansave'             => esc_html__( 'CleanSave', 'helium' ), 
		'cndig'                 => esc_html__( 'Cndig', 'helium' ), 
		'colivia'               => esc_html__( 'Colivia.de', 'helium' ), 
		'technerd'              => esc_html__( 'Communicate', 'helium' ), 
		'cosmiq'                => esc_html__( 'COSMiQ', 'helium' ), 
		'cssbased'              => esc_html__( 'CSS Based', 'helium' ), 
		'curateus'              => esc_html__( 'Curate.Us', 'helium' ), 
		'delicious'             => esc_html__( 'Delicious', 'helium' ), 
		'digaculturanet'        => esc_html__( 'DigaCultura', 'helium' ), 
		'digg'                  => esc_html__( 'Digg', 'helium' ), 
		'diggita'               => esc_html__( 'Diggita', 'helium' ), 
		'digo'                  => esc_html__( 'Digo', 'helium' ), 
		'diigo'                 => esc_html__( 'Diigo', 'helium' ), 
		'domelhor'              => esc_html__( 'doMelhor', 'helium' ), 
		'dotnetshoutout'        => esc_html__( 'DotNetShoutout', 'helium' ), 
		'douban'                => esc_html__( 'Douban', 'helium' ), 
		'draugiem'              => esc_html__( 'Draugiem.lv', 'helium' ), 
		'dropjack'              => esc_html__( 'Dropjack', 'helium' ), 
		'dudu'                  => esc_html__( 'Dudu', 'helium' ), 
		'dzone'                 => esc_html__( 'dzone', 'helium' ), 
		'efactor'               => esc_html__( 'EFactor', 'helium' ), 
		'ekudos'                => esc_html__( 'eKudos', 'helium' ), 
		'elefantapl'            => esc_html__( 'elefanta.pl', 'helium' ), 
		'email'                 => esc_html__( 'Email', 'helium' ), 
		'mailto'                => esc_html__( 'Email App', 'helium' ), 
		'embarkons'             => esc_html__( 'Embarkons', 'helium' ), 
		'evernote'              => esc_html__( 'Evernote', 'helium' ), 
		'extraplay'             => esc_html__( 'extraplay', 'helium' ), 
		'ezyspot'               => esc_html__( 'EzySpot', 'helium' ), 
		'stylishhome'           => esc_html__( 'Fab Design', 'helium' ), 
		'fabulously40'          => esc_html__( 'Fabulously40', 'helium' ), 
		'facebook'              => esc_html__( 'Facebook', 'helium' ), 
		'informazione'          => esc_html__( 'Fai Informazione', 'helium' ), 
		'thefancy'              => esc_html__( 'Fancy', 'helium' ), 
		'fark'                  => esc_html__( 'Fark', 'helium' ), 
		'farkinda'              => esc_html__( 'Farkinda', 'helium' ), 
		'fashiolista'           => esc_html__( 'Fashiolista', 'helium' ), 
		'favable'               => esc_html__( 'FAVable', 'helium' ), 
		'faves'                 => esc_html__( 'Fave', 'helium' ), 
		'favlogde'              => esc_html__( 'favlog', 'helium' ), 
		'favoritende'           => esc_html__( 'Favoriten.de', 'helium' ), 
		'favorites'             => esc_html__( 'Favorites', 'helium' ), 
		'favoritus'             => esc_html__( 'Favoritus', 'helium' ), 
		'financialjuice'        => esc_html__( 'financialjuice', 'helium' ), 
		'flaker'                => esc_html__( 'Flaker', 'helium' ), 
		'flipboard'             => esc_html__( 'Flipboard', 'helium' ), 
		'folkd'                 => esc_html__( 'Folkd', 'helium' ), 
		'formspring'            => esc_html__( 'Formspring', 'helium' ), 
		'thefreedictionary'     => esc_html__( 'FreeDictionary', 'helium' ), 
		'fresqui'               => esc_html__( 'Fresqui', 'helium' ), 
		'friendfeed'            => esc_html__( 'FriendFeed', 'helium' ), 
		'funp'                  => esc_html__( 'funP', 'helium' ), 
		'fwisp'                 => esc_html__( 'fwisp', 'helium' ), 
		'gamekicker'            => esc_html__( 'Gamekicker', 'helium' ), 
		'gg'                    => esc_html__( 'GG', 'helium' ), 
		'giftery'               => esc_html__( 'Giftery.me', 'helium' ), 
		'gigbasket'             => esc_html__( 'GigBasket', 'helium' ), 
		'givealink'             => esc_html__( 'GiveALink', 'helium' ), 
		'gmail'                 => esc_html__( 'Gmail', 'helium' ), 
		'govn'                  => esc_html__( 'Go.vn', 'helium' ), 
		'goodnoows'             => esc_html__( 'Good Noows', 'helium' ), 
		'google'                => esc_html__( 'Google', 'helium' ), 
		'googleplus'            => esc_html__( 'Google Plus', 'helium' ), 
		'googletranslate'       => esc_html__( 'Google Translate', 'helium' ), 
		'google_plusone_share'  => esc_html__( 'Google+', 'helium' ), 
		'greaterdebater'        => esc_html__( 'GreaterDebater', 'helium' ), 
		'hackernews'            => esc_html__( 'Hacker News', 'helium' ), 
		'hatena'                => esc_html__( 'Hatena', 'helium' ), 
		'gluvsnap'              => esc_html__( 'Healthimize', 'helium' ), 
		'hedgehogs'             => esc_html__( 'Hedgehogs.net', 'helium' ), 
		'historious'            => esc_html__( 'Historious', 'helium' ), 
		'hootsuite'             => esc_html__( 'HootSuite', 'helium' ), 
		'hotklix'               => esc_html__( 'Hotklix', 'helium' ), 
		'hotmail'               => esc_html__( 'Hotmail', 'helium' ), 
		'w3validator'           => esc_html__( 'HTML Validator', 'helium' ), 
		'identica'              => esc_html__( 'Identica', 'helium' ), 
		'ihavegot'              => esc_html__( 'ihavegot', 'helium' ), 
		'indexor'               => esc_html__( 'Indexor', 'helium' ), 
		'instapaper'            => esc_html__( 'Instapaper', 'helium' ), 
		'iorbix'                => esc_html__( 'iOrbix', 'helium' ), 
		'irepeater'             => esc_html__( 'IRepeater.Share', 'helium' ), 
		'isociety'              => esc_html__( 'iSociety', 'helium' ), 
		'iwiw'                  => esc_html__( 'iWiW', 'helium' ), 
		'jamespot'              => esc_html__( 'Jamespot', 'helium' ), 
		'jappy'                 => esc_html__( 'Jappy Ticker', 'helium' ), 
		'jolly'                 => esc_html__( 'Jolly', 'helium' ), 
		'jumptags'              => esc_html__( 'Jumptags', 'helium' ), 
		'kaboodle'              => esc_html__( 'Kaboodle', 'helium' ), 
		'kaevur'                => esc_html__( 'Kaevur', 'helium' ), 
		'kaixin'                => esc_html__( 'Kaixin Repaste', 'helium' ), 
		'ketnooi'               => esc_html__( 'Ketnooi', 'helium' ), 
		'kik'                   => esc_html__( 'Kik', 'helium' ), 
		'kindleit'              => esc_html__( 'Kindle It', 'helium' ), 
		'kledy'                 => esc_html__( 'Kledy', 'helium' ), 
		'kommenting'            => esc_html__( 'Kommenting', 'helium' ), 
		'latafaneracat'         => esc_html__( 'La Tafanera', 'helium' ), 
		'librerio'              => esc_html__( 'Librerio', 'helium' ), 
		'lidar'                 => esc_html__( 'LiDAR Online', 'helium' ), 
		'linkedin'              => esc_html__( 'LinkedIn', 'helium' ), 
		'linksgutter'           => esc_html__( 'Links Gutter', 'helium' ), 
		'linkshares'            => esc_html__( 'LinkShares', 'helium' ), 
		'linkuj'                => esc_html__( 'Linkuj.cz', 'helium' ), 
		'livejournal'           => esc_html__( 'LiveJournal', 'helium' ), 
		'lockerblogger'         => esc_html__( 'LockerBlogger', 'helium' ), 
		'logger24'              => esc_html__( 'Logger24.com', 'helium' ), 
		'mymailru'              => esc_html__( 'Mail.ru', 'helium' ), 
		'margarin'              => esc_html__( 'mar.gar.in', 'helium' ), 
		'markme'                => esc_html__( 'Markme', 'helium' ), 
		'mashant'               => esc_html__( 'Mashant', 'helium' ), 
		'mashbord'              => esc_html__( 'Mashbord', 'helium' ), 
		'me2day'                => esc_html__( 'me2day', 'helium' ), 
		'meinvz'                => esc_html__( 'meinVZ', 'helium' ), 
		'mekusharim'            => esc_html__( 'Mekusharim', 'helium' ), 
		'memonic'               => esc_html__( 'Memonic', 'helium' ), 
		'memori'                => esc_html__( 'Memori.ru', 'helium' ), 
		'mendeley'              => esc_html__( 'Mendeley Import', 'helium' ), 
		'meneame'               => esc_html__( 'Meneame', 'helium' ), 
		'live'                  => esc_html__( 'Messenger', 'helium' ), 
		'misterwong'            => esc_html__( 'Mister Wong', 'helium' ), 
		'misterwong_de'         => esc_html__( 'Mister Wong DE', 'helium' ), 
		'mixi'                  => esc_html__( 'Mixi', 'helium' ), 
		'moemesto'              => esc_html__( 'Moemesto.ru', 'helium' ), 
		'moikrug'               => esc_html__( 'Moikrug', 'helium' ), 
		'mrcnetworkit'          => esc_html__( 'mRcNEtwORK', 'helium' ), 
		'myspace'               => esc_html__( 'Myspace', 'helium' ), 
		'myvidster'             => esc_html__( 'myVidster', 'helium' ), 
		'n4g'                   => esc_html__( 'N4G', 'helium' ), 
		'naszaklasa'            => esc_html__( 'Nasza-klasa', 'helium' ), 
		'netlog'                => esc_html__( 'NetLog', 'helium' ), 
		'netvibes'              => esc_html__( 'Netvibes', 'helium' ), 
		'netvouz'               => esc_html__( 'Netvouz', 'helium' ), 
		'newsmeback'            => esc_html__( 'NewsMeBack', 'helium' ), 
		'newstrust'             => esc_html__( 'NewsTrust', 'helium' ), 
		'newsvine'              => esc_html__( 'Newsvine', 'helium' ), 
		'nujij'                 => esc_html__( 'Nujij', 'helium' ), 
		'odnoklassniki_ru'      => esc_html__( 'Odnoklassniki', 'helium' ), 
		'oknotizie'             => esc_html__( 'OKNOtizie', 'helium' ), 
		'openthedoor'           => esc_html__( 'OpenTheDoor', 'helium' ), 
		'oyyla'                 => esc_html__( 'Oyyla', 'helium' ), 
		'packg'                 => esc_html__( 'Packg', 'helium' ), 
		'pafnetde'              => esc_html__( 'pafnet.de', 'helium' ), 
		'pdfonline'             => esc_html__( 'PDF Online', 'helium' ), 
		'pdfmyurl'              => esc_html__( 'PDFmyURL', 'helium' ), 
		'phonefavs'             => esc_html__( 'PhoneFavs', 'helium' ), 
		'pinterest_share'       => esc_html__( 'Pinterest', 'helium' ), 
		'planypus'              => esc_html__( 'Planypus', 'helium' ), 
		'plaxo'                 => esc_html__( 'Plaxo', 'helium' ), 
		'plurk'                 => esc_html__( 'Plurk', 'helium' ), 
		'pocket'                => esc_html__( 'Pocket', 'helium' ), 
		'posteezy'              => esc_html__( 'Posteezy', 'helium' ), 
		'print'                 => esc_html__( 'Print', 'helium' ), 
		'printfriendly'         => esc_html__( 'PrintFriendly', 'helium' ), 
		'pusha'                 => esc_html__( 'Pusha', 'helium' ), 
		'qrfin'                 => esc_html__( 'QRF.in', 'helium' ), 
		'qrsrc'                 => esc_html__( 'QRSrc.com', 'helium' ), 
		'quantcast'             => esc_html__( 'Quantcast', 'helium' ), 
		'qzone'                 => esc_html__( 'Qzone', 'helium' ), 
		'reddit'                => esc_html__( 'Reddit', 'helium' ), 
		'rediff'                => esc_html__( 'Rediff MyPage', 'helium' ), 
		'redkum'                => esc_html__( 'RedKum', 'helium' ), 
		'researchgate'          => esc_html__( 'ResearchGate', 'helium' ), 
		'safelinking'           => esc_html__( 'Safelinking', 'helium' ), 
		'scoopat'               => esc_html__( 'Scoop.at', 'helium' ), 
		'scoopit'               => esc_html__( 'Scoop.it', 'helium' ), 
		'sekoman'               => esc_html__( 'Sekoman', 'helium' ), 
		'select2gether'         => esc_html__( 'Select2Gether', 'helium' ), 
		'shaveh'                => esc_html__( 'Shaveh', 'helium' ), 
		'shetoldme'             => esc_html__( 'SheToldMe', 'helium' ), 
		'sinaweibo'             => esc_html__( 'Sina Weibo', 'helium' ), 
		'skyrock'               => esc_html__( 'Skyrock Blog', 'helium' ), 
		'smiru'                 => esc_html__( 'SMI', 'helium' ), 
		'sodahead'              => esc_html__( 'SodaHead', 'helium' ), 
		'sonico'                => esc_html__( 'Sonico', 'helium' ), 
		'spinsnap'              => esc_html__( 'SpinSnap', 'helium' ), 
		'yiid'                  => esc_html__( 'Spread.ly', 'helium' ), 
		'springpad'             => esc_html__( 'springpad', 'helium' ), 
		'startaid'              => esc_html__( 'Startaid', 'helium' ), 
		'startlap'              => esc_html__( 'Startlap', 'helium' ), 
		'storyfollower'         => esc_html__( 'Story Follower', 'helium' ), 
		'studivz'               => esc_html__( 'studiVZ', 'helium' ), 
		'stuffpit'              => esc_html__( 'Stuffpit', 'helium' ), 
		'stumbleupon'           => esc_html__( 'StumbleUpon', 'helium' ), 
		'stumpedia'             => esc_html__( 'Stumpedia', 'helium' ), 
		'sulia'                 => esc_html__( 'Sulia', 'helium' ), 
		'sunlize'               => esc_html__( 'Sunlize', 'helium' ), 
		'supbro'                => esc_html__( 'SUP BRO', 'helium' ), 
		'surfingbird'           => esc_html__( 'Surfingbird', 'helium' ), 
		'svejo'                 => esc_html__( 'Svejo', 'helium' ), 
		'symbaloo'              => esc_html__( 'Symbaloo', 'helium' ), 
		'taaza'                 => esc_html__( 'Taaza', 'helium' ), 
		'tagza'                 => esc_html__( 'Tagza', 'helium' ), 
		'tapiture'              => esc_html__( 'Tapiture', 'helium' ), 
		'taringa'               => esc_html__( 'Taringa!', 'helium' ), 
		'thewebblend'           => esc_html__( 'The Web Blend', 'helium' ), 
		'thinkfinity'           => esc_html__( 'Thinkfinity', 'helium' ), 
		'thisnext'              => esc_html__( 'ThisNext', 'helium' ), 
		'thrillon'              => esc_html__( 'Thrill On', 'helium' ), 
		'throwpile'             => esc_html__( 'Throwpile', 'helium' ), 
		'toly'                  => esc_html__( 'to.ly', 'helium' ), 
		'topsitelernet'         => esc_html__( 'TopSiteler', 'helium' ), 
		'transferr'             => esc_html__( 'Transferr', 'helium' ), 
		'tuenti'                => esc_html__( 'Tuenti', 'helium' ), 
		'tulinq'                => esc_html__( 'Tulinq', 'helium' ), 
		'tumblr'                => esc_html__( 'Tumblr', 'helium' ), 
		'tvinx'                 => esc_html__( 'Tvinx', 'helium' ), 
		'twitter'               => esc_html__( 'Twitter', 'helium' ), 
		'twitthis'              => esc_html__( 'TwitThis', 'helium' ), 
		'typepad'               => esc_html__( 'Typepad', 'helium' ), 
		'upnews'                => esc_html__( 'Upnews.it', 'helium' ), 
		'urlaubswerkde'         => esc_html__( 'Urlaubswerk', 'helium' ), 
		'viadeo'                => esc_html__( 'Viadeo', 'helium' ), 
		'virb'                  => esc_html__( 'Virb', 'helium' ), 
		'visitezmonsite'        => esc_html__( 'Visitez Mon Site', 'helium' ), 
		'vk'                    => esc_html__( 'Vkontakte', 'helium' ), 
		'vkrugudruzei'          => esc_html__( 'vKruguDruzei', 'helium' ), 
		'voxopolis'             => esc_html__( 'VOXopolis', 'helium' ), 
		'vybralisme'            => esc_html__( 'vybrali SME', 'helium' ), 
		'wanelo'                => esc_html__( 'Wanelo', 'helium' ), 
		'internetarchive'       => esc_html__( 'Wayback', 'helium' ), 
		'sharer'                => esc_html__( 'WebMoney.Events', 'helium' ), 
		'webnews'               => esc_html__( 'Webnews', 'helium' ), 
		'webshare'              => esc_html__( 'WebShare', 'helium' ), 
		'werkenntwen'           => esc_html__( 'Wer Kennt Wen', 'helium' ), 
		'whatsapp'              => esc_html__( 'WhatsApp', 'helium' ), 
		'domaintoolswhois'      => esc_html__( 'Whois Lookup', 'helium' ), 
		'windows'               => esc_html__( 'Windows Gadgets', 'helium' ), 
		'wirefan'               => esc_html__( 'WireFan', 'helium' ), 
		'wishmindr'             => esc_html__( 'WishMindr', 'helium' ), 
		'wordpress'             => esc_html__( 'WordPress', 'helium' ), 
		'wowbored'              => esc_html__( 'WowBored', 'helium' ), 
		'raiseyourvoice'        => esc_html__( 'Write Politicians', 'helium' ), 
		'wykop'                 => esc_html__( 'Wykop', 'helium' ), 
		'xanga'                 => esc_html__( 'Xanga', 'helium' ), 
		'xing'                  => esc_html__( 'XING', 'helium' ), 
		'yahoobkm'              => esc_html__( 'Y! Bookmarks', 'helium' ), 
		'yahoomail'             => esc_html__( 'Y! Mail', 'helium' ), 
		'yammer'                => esc_html__( 'Yammer', 'helium' ), 
		'yardbarker'            => esc_html__( 'Yardbarker', 'helium' ), 
		'yigg'                  => esc_html__( 'Yigg', 'helium' ), 
		'yookos'                => esc_html__( 'Yookos', 'helium' ), 
		'yoolink'               => esc_html__( 'Yoolink', 'helium' ), 
		'yorumcuyum'            => esc_html__( 'Yorumcuyum', 'helium' ), 
		'youmob'                => esc_html__( 'YouMob', 'helium' ), 
		'yuuby'                 => esc_html__( 'Yuuby', 'helium' ), 
		'zakladoknet'           => esc_html__( 'Zakladok.net', 'helium' ), 
		'ziczac'                => esc_html__( 'ZicZac', 'helium' ), 
		'zingme'                => esc_html__( 'ZingMe', 'helium' )
	);
}
endif;

/* ==========================================================================
	Output AddThis Sharing Button
============================================================================= */

if( ! function_exists( 'helium_sharing_button' ) ):

function helium_sharing_button( $button ) {

	$config = array(
		'facebook_like' => array(
			'fb:like:layout' => 'button_count'
		), 
		'tweet' => array(
			'tw:count' => 'none'
		), 
		'google_plusone' => array(
			'g:plusone:size' => 'medium', 
			'g:plusone:count' => 'false'
		)
	);

	$addthis_services = helium_addthis_services();

	if( isset( $addthis_services[ $button ] ) ) {

		if( 'compact' == $button ) {
			$button = 'expanded';
		}

		echo '<a class="addthis_button_' . esc_attr( $button ) . '"';

		if( array_key_exists( $button, $config ) && is_array( $config[ $button ] ) ) {
			foreach( $config[ $button ] as $key => $value ) {
				echo ' ' . $key . '="' . esc_attr( $value ) . '"';
			}
		}

		echo '></a>';
	}
}
endif;
